### ISSUE TITLE
error scrapy list

### ISSUE THREAD

**Issue by hendisantika** [realpython/stack-spider#2]
scrap	Traceback (most recent call last):
  File "/home/hendisantika/Documents/python/ENV/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 91, in __init__
    self.update(values, priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 317, in update
    for name, value in six.iteritems(values):
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'

=========================================

How do I solve this issue?

Thanks

**Comment by SagiSatish** [comment]
This example is done on the old version of scrapy. The new version requires you to define ITEM_PIPELINES  as a dictionary, not list.  

Updated the settings.py with the below line. 
ITEM_PIPELINES = {'stack.pipelines.MongoDBPipeline':300, }

More info:
http://stackoverflow.com/questions/37442907/scrapy-attributeerror-list-object-has-no-attribute-iteritems

**Comment by mjhea0** [comment]
Do either of you want to update the blog posts? @SagiSatish @hendisantika 

https://github.com/realpython/realpython-blog/blob/master/2014/2014-12-31-web-scraping-with-scrapy-and-mongodb.markdown

https://github.com/realpython/realpython-blog/blob/master/2015/2015-02-18-web-scraping-and-crawling-with-scrapy-and-mongodb.markdown
